spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/moto_mania
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080